### ISSUE TITLE
Docker exec format error

### ISSUE THREAD

**Issue by v01t** [jeffersonjhunt/shinysdr-docker#2]
Start of docker container failed with:
standard_init_linux.go:207: exec user process caused "exec format error"

$ docker run --rm -p 8100:8100 -p 8101:8101 -v /tmp/shinysdr:/config --name shinysdr jeffersonjhunt/shinysdr:v1.5 init /config/config.py
standard_init_linux.go:207: exec user process caused "exec format error"

same result with any other command

OS: Debian 10.3
Docker:
Containers: 117
 Running: 2
 Paused: 0
 Stopped: 115
Images: 288
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 1.0.0~rc6+dfsg1-3
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.0-8-amd64
Operating System: Debian GNU/Linux 10 (buster)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.21GiB
Name: blackhawk
ID: XKA7:6ZR7:TLVT:77GL:JO7S:GQFD:VIUS:DVM4:QZ6U:L752:RP26:UTE2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by jeffersonjhunt** [comment]
I'll check this out tonight. I'm surprised it was with the AMD64 based build. Please use v1.4.2 until I get this resolved. Cheers!

**Comment by jeffersonjhunt** [comment]
This was caused by the corruption of the shinysdr-entrypoint.sh file. I will fix this and push v1.5.1 to fix it. Thanks for the feedback.
